### ISSUE TITLE
really???

### ISSUE THREAD

**Issue by iamzubin** [thisisshub/HacktoberFest#12]

**Comment by thisisshub** [comment]
@iamzubin 
had to do it for the beginners.

**Comment by iamzubin** [comment]
Sure

**Comment by Anishahaha** [comment]
Is it valid for ongoing hacktober fest 2020? @iamzubin

**Comment by OjasBarawal** [comment]
Yup, it is Valid..
You can Commit your file here

**Comment by snehal2841** [comment]
What is it about? I want to work on it.

**Comment by Deepu2002d** [comment]
I also want to add my python file in this repository.  When I am trying to push my file, its showing error-
remote: Permission to thisisshub/HacktoberFest.git denied to Deepu2002d.
fatal: unable to access 'https://github.com/thisisshub/HacktoberFest/': The requested URL returned error: 403
Sir, I need help. What should I do?

**Comment by Prachi-05** [comment]
@Deepu2002d You need to fork the repo first and push it in the forked repo.

**Comment by Deepu2002d** [comment]
Oh, Thank you really.
If I am doing it via CLI using git clone and other commands, do I still have to fork the repository first?

**Comment by Prachi-05** [comment]
Yeah. You do. Fork it, clone the forked repo and make changes to that. And
then create a PR from your forked repo to the actual one.

**Comment by Deepu2002d** [comment]
Thanks. One more thing I want to know - Do you know how much time it takes for them to accept our pull request?

**Comment by Deepu2002d** [comment]
Is there any maintainer in here who can check my contribution and than accept it?
I made the PR 2 days before and it's still showing 12 days to become mature but only 7-8 days are left for October to end so, I need help from someone to mark my PR accepted after checking it.
I am new and don't know where to contact a maintainer .

**Comment by thisisshub** [comment]
@Deepu2002d I added the `hacktoberfest-accepted` label in merged PRs. It would solve your issue.

**Comment by Deepu2002d** [comment]
@thisisshub Thank you for notifying me. :-)

**Comment by PriyaGandhi311** [comment]
hey, if i add a file with double liked list code in this repo in cpp then will it be eligibke for hacktoberfest2020? @thisisshub

**Comment by thisisshub** [comment]
@PriyaGandhi311 yeah.

**Comment by shresth2102001** [comment]
hey @thisisshub  i am upload a python code for tree transversal

**Comment by shresth2102001** [comment]
> hey @thisisshub i am upload a python code for tree transversal

will that work for hacktoberfest

**Comment by shresth2102001** [comment]
hey @thisisshub  I am request two more pull request for hacktoberfest pls merge my pull req.

**Comment by priya-mane** [comment]
I would like to add a flask based web app for twitter user dashboard.I am using twitter OAuth as well.
Where can I add this project?

**Comment by Rahullaha06** [comment]
is it valid for Hacktoberfest 2021

**Comment by FirdausJawed** [comment]
if valid for hacktober fest 2021

then i am eager to work here

**Comment by dev-redakai** [comment]
yes it's working for hacktober fest 2021

**Comment by ashan-tharaka** [comment]
@iamzubin what to do? this valid for hacktoberfest 2021

**Comment by HastiSutaria** [comment]
@iamzubin @thisisshub Can we create PR for any problems?

**Comment by iamzubin** [comment]
1. why are people tagging me? 
2. please read the rules for hacktoberfest they keep changing.
