### ISSUE TITLE
Minimum group flips to make same array

### ISSUE THREAD

**Issue by RYzen-009** [thisisshub/HacktoberFest#1456]
I want to participate in the  hacktober fest and that's why I am opening this issue and will provide a efficient approach to solve this question with proper explanation ..

**Comment by RYzen-009** [comment]
I want to work on this issue

**Comment by aromalsanthosh** [comment]
1. Go to https://hacktoberfest.digitalocean.com/ 
2. Sign Up with github
3. register for event
4. fork this repo
5. add any piece of code in any of the programming languagges in this repo .
6. make a pull request, it will be automatically merged by mergify bot
7. repeat 5&6 4 times
8. you have succesfully done the task
9. your pull requests will mature in 14 days, you will be eligible for swags

**Comment by aromalsanthosh** [comment]
> 1. Go to https://hacktoberfest.digitalocean.com/
> 2. Sign Up with github
> 3. register for event
> 4. fork this repo
> 5. add any piece of code in any of the programming languagges in this repo .
> 6. make a pull request, it will be automatically merged by mergify bot
> 7. repeat 5&6 4 times
> 8. you have succesfully done the task
> 9. your pull requests will mature in 14 days, you will be eligible for swags

@RYzen-009

**Comment by HiruniPerera** [comment]
Hi RYzen-009 i would lov to contribute to this can i contribute o this?

**Comment by RYzen-009** [comment]
@HiruniPerera sorry but I have already merged the pr for the same
